import type { WorkspaceSnapshot } from "./schema.js"
import { protocolVersion } from "./schema.js"

const now = "2026-08-25T21:52:00.000Z"

export const demoWorkspace: WorkspaceSnapshot = {
  protocolVersion,
  machine: {
    id: "machine-local",
    name: "macbook-pro-m3",
    platform: "darwin",
    arch: "arm64",
    version: "0.0.1",
    connection: "local",
    reachable: true,
  },
  project: {
    id: "project-acme-api",
    machineId: "machine-local",
    name: "acme-api",
    path: "/Users/dev/src/acme-api",
    branch: "main",
  },
  activeSessionId: "session-billing",
  sessions: [
    {
      id: "session-billing",
      projectId: "project-acme-api",
      title: "Migrate billing webhooks to idempotent handlers with replay protection",
      state: "waiting",
      runtime: {
        provider: "claude-code",
        model: "sonnet-4.6",
        reasoning: "high",
        permissionMode: "build",
        auto: false,
      },
      changedFiles: 7,
      testsPassed: 42,
      testsFailed: 1,
      updatedAt: now,
    },
    {
      id: "session-onboarding",
      projectId: "project-acme-api",
      title: "design-studio: onboarding v3, three variants for the empty state",
      state: "active",
      runtime: {
        provider: "codex",
        model: "gpt-5.3-codex",
        reasoning: "medium",
        permissionMode: "plan",
        auto: false,
      },
      changedFiles: 3,
      testsPassed: 18,
      testsFailed: 0,
      updatedAt: "2026-08-25T21:48:00.000Z",
    },
    {
      id: "session-audit",
      projectId: "project-acme-api",
      title: "repo-audit: dependency and license review",
      state: "idle",
      runtime: {
        provider: "opencode",
        model: "glm-4.7",
        reasoning: "medium",
        permissionMode: "ask",
        auto: false,
      },
      changedFiles: 0,
      testsPassed: 0,
      testsFailed: 0,
      updatedAt: "2026-08-25T20:34:00.000Z",
    },
  ],
  approvals: [
    {
      id: "approval-migrate",
      sessionId: "session-billing",
      risk: "hard-gate",
      operation: "Apply a production database migration",
      command: "pnpm prisma migrate deploy",
      machine: "macbook-pro-m3",
      agent: "claude-code / sonnet-4.6",
      mode: "build",
      directory: "/Users/dev/.domovoi/worktrees/wt-billing-idem",
      affects: "Production database schema: replay_events and webhook idempotency index.",
      network: "api.stripe.com and production PostgreSQL",
      estimatedDuration: "20–40 seconds",
      checkpoint: "ckpt_7f21",
      requestedAt: now,
    },
  ],
  approvalRules: [],
  thread: [
    {
      id: "thread-checkpoint",
      kind: "checkpoint",
      label: "ckpt_7f21 · before provider handoff · 12:41",
      createdAt: "2026-08-25T21:41:00.000Z",
    },
    {
      id: "thread-user",
      kind: "user",
      body: "The Stripe retries are double-charging. Make every webhook idempotent, add a replay table, and do not touch production config before you propose anything.",
      createdAt: "2026-08-25T21:42:00.000Z",
    },
    {
      id: "thread-handoff",
      kind: "system",
      body: "Handed off codex / gpt-5.3-codex to claude-code / sonnet-4.6.",
      detail: "Thread, plan, worktree, diff, test results, and 2 open annotations carried over. Hidden reasoning and provider caches did not transfer.",
      createdAt: "2026-08-25T21:44:00.000Z",
    },
    {
      id: "thread-assistant",
      kind: "assistant",
      body: "Suite is green except webhooks/replay.spec.ts; it asserts the old at-least-once behavior. Three needs a migration, so I will stop and ask.",
      createdAt: "2026-08-25T21:50:00.000Z",
    },
  ],
  artifacts: [
    {
      id: "artifact-plan",
      sessionId: "session-billing",
      title: "Idempotent webhook migration",
      type: "plan",
      revision: 3,
    },
    {
      id: "artifact-preview",
      sessionId: "session-billing",
      title: "Replay operations preview",
      type: "preview",
      revision: 2,
    },
  ],
}
