import assert from "node:assert/strict"
import { mkdtemp, mkdir, writeFile, readFile, rm } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import test from "node:test"

import { belowPattern, checkDesignRule, floorFrom, fontTokenSizes, generate, writeDesignRule } from "./design-rule.mjs"

const manifest = { "x-omelette": { tokenKinds: { "--text-micro": "font", "--text-mono-xs": "font", "--text-eyebrow": "font", "--primary": "color" } } }
const typography = ":root {\n  --text-micro: 10.5px;\n  --text-mono-xs: 10px;\n  --text-eyebrow: 9.5px;\n}\n"

test("reads only the tokens the manifest calls fonts", () => {
  const sizes = fontTokenSizes(manifest, typography)
  assert.deepEqual([...sizes.keys()].sort(), ["--text-eyebrow", "--text-micro", "--text-mono-xs"])
})

test("refuses a font token the stylesheet never defines", () => {
  const withHole = { "x-omelette": { tokenKinds: { ...manifest["x-omelette"].tokenKinds, "--text-ghost": "font" } } }
  assert.throws(() => fontTokenSizes(withHole, typography), /--text-ghost/)
})

test("takes the boundary from the smallest named role, not from a literal", () => {
  const { floor, smallest, named } = floorFrom(fontTokenSizes(manifest, typography))
  assert.equal(floor, 10.5)
  assert.equal(smallest, 9.5)
  assert.deepEqual(named.map((role) => role.token), ["--text-eyebrow", "--text-mono-xs"])
})

test("moves the boundary when the design system moves it", () => {
  const moved = typography.replace("--text-eyebrow: 9.5px", "--text-eyebrow: 8.5px")
  assert.equal(floorFrom(fontTokenSizes(manifest, moved)).smallest, 8.5)
})

test("refuses a floor with no named role beneath it", () => {
  const bare = { "x-omelette": { tokenKinds: { "--text-micro": "font" } } }
  assert.throws(() => floorFrom(fontTokenSizes(bare, typography)), /no named role/)
})

test("matches every class below the boundary and nothing at or above it", () => {
  // The bare alternation is not the rule. The generator wraps it so the px and
  // the closing bracket anchor it, and an unanchored test would pass on the 9
  // inside 9.5 while the real selector does not.
  const pattern = new RegExp(`text-\\[(?:${belowPattern(9.5).replaceAll("\\\\", "\\")})px\\]`)
  for (const legal of ["9.5", "10", "10.5", "11", "12"]) assert.equal(pattern.test(`text-[${legal}px]`), false, `text-[${legal}px] must not match`)
  for (const drift of ["8", "9", "9.4", "0.5"]) assert.equal(pattern.test(`text-[${drift}px]`), true, `text-[${drift}px] must match`)
})

test("refuses a boundary it cannot express rather than emitting a pattern nobody checked", () => {
  assert.throws(() => belowPattern(10.5), /extend belowPattern/)
})

test("check reports staleness and names the command that fixes it", async () => {
  const root = await mkdtemp(join(tmpdir(), "domovoi-design-rule-"))
  try {
    await mkdir(join(root, "design/design_system_domovoi/tokens"), { recursive: true })
    await writeFile(join(root, "design/design_system_domovoi/_adherence.oxlintrc.json"), JSON.stringify(manifest))
    await writeFile(join(root, "design/design_system_domovoi/tokens/typography.css"), typography)

    const missing = await checkDesignRule(root)
    assert.match(missing[0], /missing; run pnpm design:rule/)

    await writeDesignRule(root)
    assert.deepEqual(await checkDesignRule(root), [])

    await writeFile(join(root, "eslint.type-floor.generated.mjs"), "export const typeFloorRules = []\n")
    const stale = await checkDesignRule(root)
    assert.match(stale[0], /stale relative to .*_adherence\.oxlintrc\.json; run pnpm design:rule/)
  } finally {
    await rm(root, { recursive: true, force: true })
  }
})

test("the generated module says where it came from and what it bans", async () => {
  const root = await mkdtemp(join(tmpdir(), "domovoi-design-rule-"))
  try {
    await mkdir(join(root, "design/design_system_domovoi/tokens"), { recursive: true })
    await writeFile(join(root, "design/design_system_domovoi/_adherence.oxlintrc.json"), JSON.stringify(manifest))
    await writeFile(join(root, "design/design_system_domovoi/tokens/typography.css"), typography)
    const { module } = await generate(root)
    assert.match(module, /Generated by pnpm design:rule\. Do not edit\./)
    assert.match(module, /--text-eyebrow 9\.5px, --text-mono-xs 10px/)
    assert.match(module, /text-eyebrow or text-mono-xs/)
    await writeDesignRule(root)
    assert.equal(await readFile(join(root, "eslint.type-floor.generated.mjs"), "utf8"), module)
  } finally {
    await rm(root, { recursive: true, force: true })
  }
})
