// Generated by scripts/mobile-tokens.mjs from packages/ui/src/styles.css. Do not edit.
// Run pnpm mobile:tokens after changing the stylesheet; release:invariants
// fails when this file and the stylesheet disagree.

export type AlphaStep = 12 | 14 | 16 | 18 | 20 | 30 | 35 | 45 | 60 | 78 | 82 | 84 | 88 | 94
export type LoadedFont = "InstrumentSans_400Regular" | "InstrumentSans_500Medium" | "InstrumentSans_600SemiBold" | "JetBrainsMono_400Regular"
export type FontUtility = "sans" | "sans-medium" | "sans-semibold" | "mono"
export interface FontFace {
  readonly utility: FontUtility
  readonly family: string
  readonly weight: number
  readonly name: LoadedFont
  readonly package: string
  readonly file: string
}

export declare const colors: {
  readonly light: {
    readonly background: "#fbfaf8"
    readonly foreground: "#1a1a1f"
    readonly card: "#ffffff"
    readonly "card-foreground": "#1a1a1f"
    readonly popover: "#ffffff"
    readonly "popover-foreground": "#1a1a1f"
    readonly primary: "#4e56d3"
    readonly "primary-foreground": "#fbfcff"
    readonly secondary: "#eeede9"
    readonly "secondary-foreground": "#323238"
    readonly muted: "#e7e6e2"
    readonly "muted-foreground": "#5d5d63"
    readonly accent: "#eeede9"
    readonly "accent-foreground": "#1a1a1f"
    readonly destructive: "#c51d28"
    readonly "destructive-foreground": "#fff9f8"
    readonly border: "#d6d4d0"
    readonly input: "#d6d4d0"
    readonly ring: "#4e56d3"
    readonly sidebar: "#f4f3f0"
    readonly "sidebar-foreground": "#323238"
    readonly "sidebar-border": "#d6d4d0"
    readonly "sidebar-accent": "#eeede9"
    readonly "sidebar-accent-foreground": "#1a1a1f"
    readonly success: "#007a43"
    readonly "success-foreground": "#f7fef9"
    readonly warning: "#a15700"
    readonly "warning-foreground": "#fffaf5"
    readonly info: "#0068ad"
    readonly "info-foreground": "#f6fdff"
    readonly strong: "#323238"
    readonly faint: "#7f7f86"
    readonly code: "#f1f0ed"
    readonly desk: "#e1dfdc"
    readonly overlay: "#2d2d3361"
    readonly "warn-fill": "#fec348"
    readonly "warn-fill-fg": "#4c2904"
    readonly "warn-bg": "#fff6df"
    readonly "warn-border": "#f3cf9f"
    readonly "warn-fg": "#723f00"
    readonly "warn-dim": "#885620"
    readonly "warn-bg-deep": "#fbebcb"
    readonly "danger-bg": "#fff2f0"
    readonly "danger-border": "#fdc9c4"
    readonly "danger-fg": "#9b1e22"
    readonly "danger-dim": "#ae4440"
    readonly "danger-on": "#fff9f8"
    readonly "info-bg": "#edf9ff"
    readonly "info-border": "#bedcf3"
    readonly "info-fg": "#12527a"
    readonly "info-dim": "#006495"
  }
  readonly dark: {
    readonly background: "#0e0e10"
    readonly foreground: "#f1f1f4"
    readonly card: "#17171a"
    readonly "card-foreground": "#f1f1f4"
    readonly popover: "#17171a"
    readonly "popover-foreground": "#f1f1f4"
    readonly primary: "#8798ff"
    readonly "primary-foreground": "#0c0e1c"
    readonly secondary: "#1e1e21"
    readonly "secondary-foreground": "#dadadd"
    readonly muted: "#252529"
    readonly "muted-foreground": "#919198"
    readonly accent: "#1e1e21"
    readonly "accent-foreground": "#f1f1f4"
    readonly destructive: "#e54c4a"
    readonly "destructive-foreground": "#fff6f5"
    readonly border: "#2e2f33"
    readonly input: "#2e2f33"
    readonly ring: "#8798ff"
    readonly sidebar: "#121215"
    readonly "sidebar-foreground": "#dadadd"
    readonly "sidebar-border": "#2e2f33"
    readonly "sidebar-accent": "#1e1e21"
    readonly "sidebar-accent-foreground": "#f1f1f4"
    readonly success: "#51c88b"
    readonly "success-foreground": "#04130a"
    readonly warning: "#f6a65d"
    readonly "warning-foreground": "#231103"
    readonly info: "#67addd"
    readonly "info-foreground": "#03111b"
    readonly strong: "#dadadd"
    readonly faint: "#6b6b72"
    readonly code: "#0a0a0c"
    readonly desk: "#040405"
    readonly overlay: "#040405c7"
    readonly "warn-fill": "#f6a65d"
    readonly "warn-fill-fg": "#231103"
    readonly "warn-bg": "#2d1905"
    readonly "warn-border": "#60370b"
    readonly "warn-fg": "#ffe6c8"
    readonly "warn-dim": "#d2a883"
    readonly "warn-bg-deep": "#1d1106"
    readonly "danger-bg": "#491513"
    readonly "danger-border": "#782a28"
    readonly "danger-fg": "#ffdedb"
    readonly "danger-dim": "#dba9a4"
    readonly "danger-on": "#3a0e0d"
    readonly "info-bg": "#121c23"
    readonly "info-border": "#18364a"
    readonly "info-fg": "#b4d6ef"
    readonly "info-dim": "#8ec5ec"
  }
}
export declare const radius: {
  readonly sm: "6.4px"
  readonly md: "7.4px"
  readonly lg: "8.4px"
  readonly xl: "10.4px"
  readonly "2xl": "14px"
}
export interface Shadow {
  readonly shadowColor: string
  readonly shadowOpacity: number
  readonly shadowRadius: number
  readonly shadowOffset: { readonly width: number; readonly height: number }
  readonly elevation: number
}
export declare const shadows: {
  readonly light: { readonly md: Shadow; readonly lg: Shadow; readonly xl: Shadow }
  readonly dark: { readonly md: Shadow; readonly lg: Shadow; readonly xl: Shadow }
}
// Tokens the stylesheet asks for outside sRGB. The phone paints the clipped
// hex above; a browser on a wide-gamut display paints more chroma.
export declare const outOfGamut: {
  readonly light: readonly ["primary-foreground", "destructive-foreground", "success", "warning", "warning-foreground", "info", "info-foreground", "warn-bg", "warn-fg", "danger-bg", "danger-on", "info-bg", "info-dim"]
  readonly dark: readonly ["primary", "destructive-foreground", "ring", "warn-fg", "danger-fg"]
}
export declare const alphaSteps: readonly AlphaStep[]
export declare function withAlpha(color: string, percent: AlphaStep): string
export declare const fonts: readonly FontFace[]
export declare const fontFamily: {
  readonly sans: "InstrumentSans_400Regular"
  readonly "sans-medium": "InstrumentSans_500Medium"
  readonly "sans-semibold": "InstrumentSans_600SemiBold"
  readonly mono: "JetBrainsMono_400Regular"
}
